<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?= $pageTitle ?? 'QuizMe' ?></title>

    <link rel="shortcut icon" href="favicon.png" type="image/x-icon">

    <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/style.css">
</head>

<body>